### ISSUE TITLE
Dynamic catalog CREATE/DROP

### ISSUE THREAD

**Issue by maulikknorket** [treasure-data/trino-client-ruby#106]
Now Trino supports creating/Deleting catalogs,

Does anyone knows `trino-client-ruby` support's it?
If yes then please provide steps on how it works with trino-client-ruby.

Thanks

**Comment by miniway** [comment]
trino-client-ruby can only send a SQL and fetch result from it as like trino-client-java. If the Trino supports SQL syntax to create/drop catalog (afaik it’s not supported yet), trino-client-ruby could support it.

**Comment by exoego** [comment]
Closing as answered
