### ISSUE TITLE
How to Using Oauth2 with this client

### ISSUE THREAD

**Issue by yemaney** [treasure-data/trino-client-ruby#121]
The docs show that the current client has options to set the user and password for basic authentication. 
Was wondering if oauth2 could also be an option.

If not, would adding an oauth2 token to the `http_headers` option suffice to enable sending oauth2 authentication info to the trino cluster?
If so, what sort of headers should be added to headers?

**Comment by yuokada** [comment]
Sorry for the late response. This client library doesn't support OAuth 2.0 authentication. 
And, we have no plan to support it.

**Comment by jhbigler** [comment]
If the JWT is already generated, you can just load in the token and add it to the Authorization header. Example http_header setting:
```
token = File.read '/path/to/token'

client = Trino::Client.new(
  #...
  http_headers: {
    'Authorization' => "Bearer #{token}"
  },
)
```

It'd be kinda nice if this was part of the API (just add a `token: '...'` parameter and the library crafts the header for the user) but this is an easy workaround.

**Comment by exoego** [comment]
Closing as the question answered.
We are happy to review and merge OAuth2 support if someone volunteers
